export default {
  colorBlueOne: '#ECF8FF',
  colorBlueTwo: '#B4DCED',
  colorBlueThree: '#8BCAE8',
  colorBlueFour: '#60B4DE',
  colorBlueFive: '#349ACC',
  defaultPrimaryColor: '#007ECC',
  darkPrimaryColor: '#292C44',
  almostBlack: 'rgba(0, 0, 0, 0.9)',
  colorDanger: '#ff4c4c',
  colorDangerMuted: '#ffbfbf',
  colorBlue: '#4f80e1',
  colorBlueMuted: 'rgba(79, 128, 225, 0.4)',
  colorLightGrey: 'rgba(0,0,0,0.1)',
  fontFamily: `
      -apple-system, BlinkMacSystemFont,
      "Segoe UI",
      Roboto, "Droid Sans",
      Ubuntu, Cantarell,
      "Fira Sans",
      Helvetica, Arial, sans-serif`,
  fontWeightLight: '300',
  fontWeightNormal: '400',
  fontWeightMedium: '500',
  fontSizeCommon: '16px',
  fontSizeMedium: '14px',
  fontSizeSmall: '12px',
  fontSizeTiny: '10px',
};
