export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_RESET_PASSWORD = 'USER_RESET_PASSWORD';

export const PRODUCTS_RETREIVED = 'PRODUCTS_RETREIVED';
export const PRODUCT_RETREIVED = 'PRODUCT_RETREIVED';

export const PRODUCT_SELECTED = 'PRODUCT_SELECTED';

export const SIZES_RETREIVED = 'SIZES_RETREIVED';

export const DESIGNS_RETREIVED = 'DESIGNS_RETREIVED';
