export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_RESET_PASSWORD = 'USER_RESET_PASSWORD';

export const PRODUCTS_RETREIVED = 'PRODUCTS_RETREIVED';

export const PRODUCT_SELECTED = 'PRODUCT_SELECTED';
